```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(viridis)
```

```{r}
sample <- readRDS("ChiR_IWP_2017.rds")
Idents(object = sample) <- sample@meta.data$SCT_snn_res.0.5
macs <- subset(sample, idents = c("0", "1", "2", "5", "6", "7", "8", "9", "10"))
DimPlot(macs, reduction = "umap", label = TRUE) + NoLegend()
```

```{r}
DimPlot(macs, reduction = "umap", label = TRUE, group.by = "orig.ident") + NoLegend()
```

```{r}
Idents(object = macs) <- macs@meta.data$orig.ident
macs.markers <- FindAllMarkers(macs, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.05)
```

```{r}
top10 <- macs.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
DoHeatmap(macs, features = top10$gene) + NoLegend() + scale_fill_viridis()
```

```{r}
write.csv(macs.markers, file = file.path("/Users/jamrute/Desktop", "ChiR_vs_IWP_macs_2017_DGE.csv"), quote = FALSE)
```

```{r}
Idents(object = macs) <- macs@meta.data$SCT_snn_res.0.5
macs.markers <- FindAllMarkers(macs, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.05)
write.csv(macs.markers, file = file.path("/Users/jamrute/Desktop", "2017_clusters_DGE.csv"), quote = FALSE)
```

```{r}
top10 <- macs.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)
DoHeatmap(macs, features = top10$gene) + NoLegend() + scale_fill_viridis()
```

```{r}
desired_genes <- c("MT2A","MT1X","ALOX5AP","RETN","MALAT1","TREM2","WSB1","BTG1","SLC11A1","CAPG","RPSA","RPS2","MT1G","EEF1B2","CD74","SPP1","MT-ND6","ENO1","SLC25A37","ASGR2","ACTG1","RPL3","MS4A7","PGK1","SAT1","THBS1","RPLP0","BNIP3","VMP1","RPL10A","RPL4","NKG7","MT1E","RPL6","LGALS1","ALDH2","RPS18","RPS3","PGAM1","NT5DC2","ADAM28","RPS19","RPS6","PLAUR","CD14","RPS10","DDIT4","PLXDC2","GAPDH","A2M","RPS8","DENND3","SCD","RPL5","S100A10","CLEC5A","PVALB","MT-CO2","MT-ND4","IFITM3","LYVE1","FTL","SELENOP","CSTB","MT-CYB","MT-CO1","MT-CO3","CD36","DAB2","MT-ND5","MT-ATP6","IFITM2","LILRB5","CFD","F13A1","CTSZ","EGFL7","MT-ND3","IGFBP4","PLTP","FCGR2B","MT-ND2","TMEM70","CTSB","FOLR2","HSD17B4","LGMN","NINJ1","SIGLEC1","LGALS9","GATM","ATP1B1","FSCN1","ABCA1","BLVRB","CDA","B3GNT7","NPL","ISG15","C2","HSPA1A","MAF","CCND1","POLR2L","RGL1","COLEC12","SNX3","FRMD4B")
DoHeatmap(macs, features = desired_genes, group.by = "orig.ident") + NoLegend() + scale_fill_viridis() + theme(text = element_text(size = 4))
```

```{r}
write.csv(macs@meta.data, file = file.path("/Users/jamrute/Desktop", "ChiR_IWP_macs_meta.csv"), quote = FALSE)
```





